# Generated by Django 3.2.13 on 2022-05-10 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CreateUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter your name', max_length=20)),
                ('email', models.EmailField(max_length=250)),
                ('password', models.CharField(max_length=20)),
                ('city', models.CharField(help_text='Enter your home town location', max_length=30)),
            ],
        ),
    ]
