# Generated by Django 3.2.13 on 2022-05-27 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mpsblog', '0005_auto_20220512_1917'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.SlugField(max_length=300, null=True),
        ),
    ]
