# Generated by Django 3.2.13 on 2022-05-27 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mpsblog', '0006_post_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(max_length=300, null=True, unique=True),
        ),
    ]
