# Generated by Django 3.2.13 on 2022-05-30 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mpsblog', '0009_alter_post_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='likes',
        ),
    ]
